
service: api-express

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: api-express
  lambdaHashingVersion: 20201221
  region: sa-east-1


functions:
  app-api:
    # Este handler por el module.handler de handler.js handler.funcion
    handler: handler.handler
    events:
      - http:
            path: /
            method: GET
            cors: true
      - http:
            path: /{proxy+}
            method: any
            cors: true
      - http:
            path: /post
            method: POST
            cors: true
